// crispieri-vue/frontend/src/components/cotizador/ReviewStep.vue
<template>
  <div class="space-y-3">
    <div class="flex items-center gap-2">
      <span class="w-7 h-7 rounded-full bg-emerald-600 text-white text-xs font-bold flex items-center justify-center">8</span>
      <h3 class="text-sm font-semibold text-gray-800">Revisión y envío</h3>
    </div>

    <div class="bg-white border border-gray-200 rounded-xl p-4 space-y-3">
      <div v-if="store.currentProductType" class="flex justify-between text-sm">
        <span class="text-gray-500">Tipo</span>
        <span class="font-medium">{{ store.currentProductType.name }}</span>
      </div>
      <div v-if="store.currentProductLine" class="flex justify-between text-sm">
        <span class="text-gray-500">Línea</span>
        <span class="font-medium">{{ store.currentProductLine.name }}</span>
      </div>
      <div class="flex justify-between text-sm">
        <span class="text-gray-500">Dimensiones</span>
        <span class="font-medium">{{ store.widthMm }}×{{ store.heightMm }}mm · {{ store.panelCount }} paño(s)</span>
      </div>
      <div v-if="store.currentColor" class="flex justify-between text-sm">
        <span class="text-gray-500">Color</span>
        <span class="font-medium">{{ store.currentColor.name }}</span>
      </div>
      <div v-if="store.currentGlassOption" class="flex justify-between text-sm">
        <span class="text-gray-500">Vidrio</span>
        <span class="font-medium">{{ store.currentGlassOption.name }}</span>
      </div>
      <div v-if="store.selectedAccessories.length > 0" class="flex justify-between text-sm">
        <span class="text-gray-500">Accesorios</span>
        <span class="font-medium">{{ store.selectedAccessories.length }} seleccionados</span>
      </div>
      <div class="flex justify-between text-sm">
        <span class="text-gray-500">Cantidad</span>
        <span class="font-medium">{{ store.quantity }} unidad(es)</span>
      </div>
    </div>

    <div class="flex gap-3 pt-1">
      <button
        @click="store.saveDraft()"
        class="px-5 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-xl hover:bg-gray-50 transition-colors"
      >
        Guardar borrador
      </button>
      <button
        @click="handlerSubmit"
        :disabled="store.submitting || !canSubmit"
        class="flex-1 px-5 py-2.5 text-sm font-semibold text-white bg-[#0D5C63] rounded-xl hover:bg-[#0A4A50] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        <span v-if="store.submitting" class="flex items-center justify-center gap-2">
          <span class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
          Enviando...
        </span>
        <span v-else>Enviar cotización</span>
      </button>
    </div>

    <div v-if="store.submitError" class="text-xs text-red-500">{{ store.submitError }}</div>

    <div v-if="store.lastQuote" class="bg-emerald-50 border border-emerald-200 rounded-xl p-4">
      <p class="text-sm font-semibold text-emerald-700 mb-2">Cotización enviada exitosamente</p>
      <p class="text-xs text-emerald-600">ID: {{ store.lastQuote.id }}</p>
      <button
        @click="store.resetConfig()"
        class="mt-3 px-4 py-1.5 text-xs font-medium text-emerald-700 bg-emerald-100 rounded-lg hover:bg-emerald-200 transition-colors"
      >
        Nueva cotización
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useQuoteStore } from '@/stores/quoteStore'

const store = useQuoteStore()

const canSubmit = computed(() =>
  !!store.productTypeId && !!store.productLineId &&
  store.widthMm > 0 && store.heightMm > 0 &&
  !!store.colorId && !!store.glassOptionId &&
  store.quantity > 0
)

async function handlerSubmit() {
  await store.submitQuote()
}
</script>

// src/components/cotizador/ReviewStep.tsx
'use client';

import { useQuoteStore, getCurrentProductType, getCurrentProductLine, getCurrentColor, getCurrentGlassOption, getAvailableAccessoriesForState, getCompletedSteps } from '@/stores/quoteStore';
import { CheckCircle, AlertCircle } from 'lucide-react';

export default function ReviewStep() {
  const store = useQuoteStore();
  const productType = getCurrentProductType(store);
  const productLine = getCurrentProductLine(store);
  const color = getCurrentColor(store);
  const glass = getCurrentGlassOption(store);
  const availableAccessories = getAvailableAccessoriesForState(store);
  const selectedAccessoryIds = store.selectedAccessories.map((a) => a.accessoryId);
  const selectedAccessoryNames = availableAccessories
    .filter((a) => selectedAccessoryIds.includes(a.id))
    .map((a) => a.name);
  const completedSteps = getCompletedSteps(store);
  const allComplete = completedSteps.includes(8);
  const estimate = store.priceEstimate;

  const fmt = (n: number) => `$${Math.round(n).toLocaleString('es-CL')}`;

  const steps = [
    { num: 1, label: 'Tipo de producto', value: productType?.name, required: true },
    { num: 2, label: 'Línea / Serie', value: productLine?.name, required: true },
    { num: 3, label: 'Dimensiones', value: `${store.heightMm} mm × ${store.widthMm} mm`, required: true },
    { num: 4, label: 'Color del perfil', value: color?.name, required: true },
    { num: 5, label: 'Vidrio', value: glass?.name, required: true },
    { num: 6, label: 'Accesorios', value: selectedAccessoryNames.length > 0 ? selectedAccessoryNames.join(', ') : 'Ninguno', required: false },
    { num: 7, label: 'Cantidad', value: `${store.quantity} unidades`, required: true },
  ];

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <span className="w-7 h-7 rounded-full bg-[#0D5C63] text-white text-xs font-bold flex items-center justify-center">
          8
        </span>
        <h3 className="text-sm font-semibold text-gray-800">Revisión final</h3>
      </div>

      <div className={`p-4 rounded-xl border-2 ${allComplete ? 'border-emerald-200 bg-emerald-50/50' : 'border-amber-200 bg-amber-50/50'}`}>
        <div className="flex items-center gap-2 mb-3">
          {allComplete ? (
            <>
              <CheckCircle className="w-5 h-5 text-emerald-500" />
              <span className="text-sm font-semibold text-emerald-700">Configuración completa</span>
            </>
          ) : (
            <>
              <AlertCircle className="w-5 h-5 text-amber-500" />
              <span className="text-sm font-semibold text-amber-700">Pendiente</span>
            </>
          )}
        </div>

        <div className="space-y-2">
          {steps.map((step) => {
            const isComplete = step.required ? !!step.value : true;
            return (
              <div key={step.num} className="flex items-center justify-between py-1.5 border-b border-gray-100 last:border-0">
                <div className="flex items-center gap-2">
                  <span className={`w-5 h-5 rounded-full text-[10px] font-bold flex items-center justify-center ${
                    isComplete ? 'bg-emerald-100 text-emerald-600' : 'bg-amber-100 text-amber-600'
                  }`}>
                    {isComplete ? '✓' : step.num}
                  </span>
                  <span className="text-xs text-gray-500">{step.label}</span>
                </div>
                <span className={`text-xs font-medium ${isComplete ? 'text-gray-700' : 'text-amber-500'}`}>
                  {step.value || 'Sin completar'}
                </span>
              </div>
            );
          })}
        </div>

        {estimate && allComplete && (
          <div className="mt-4 pt-3 border-t border-emerald-200">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-700">Total estimado (con IVA)</span>
              <span className="text-lg font-bold text-emerald-600">{fmt(estimate.total + estimate.tax)}</span>
            </div>
            {store.quantity > 1 && (
              <div className="text-xs text-gray-400 text-right">{fmt(estimate.unitTotal + Math.round(estimate.unitTotal * 0.19))} c/u</div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
